name: deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Decode google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > ./app/google-services.json

      - name: Decode service account key
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
        run: echo $SERVICE_ACCOUNT > ./app/service-account-key.json
      
      - name: Decode keystore properties
        env:
          KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
        run: echo $KEYSTORE_PROPERTIES > ./keystore.properties

      - name: Publish Bundle
        run: bash ./gradlew build publishReleaseBundle
